# Generated by Django 4.2.1 on 2023-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='status',
            field=models.CharField(choices=[('created', 'Created 🔵'), ('no_payment', "Hasn't Paid 🔴"), ('on_going', 'On-Going 🟠'), ('completed', 'Completed 🟢')], default='created', max_length=20),
        ),
    ]
