# Generated by Django 4.2.1 on 2023-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assasin', '0002_alter_hit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='status',
            field=models.CharField(choices=[('no_payment', "Hasn't Paid 🔴"), ('on_going', 'On-Going 🟠'), ('completed', 'Completed 🟢')], default='no_payment', max_length=20),
        ),
    ]
