# Generated by Django 4.2.1 on 2023-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assasin', '0003_alter_hit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='track_number',
            field=models.IntegerField(default=11111, unique=True),
        ),
    ]
